---
- hosts: all
  vars_files:
    - vars.json
  tasks:
    - name: Import RabbitMQ keys
      become: yes
      shell: |
        rpm --import 'https://github.com/rabbitmq/signing-keys/releases/download/3.0/rabbitmq-release-signing-key.asc'
        rpm --import 'https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key'
        rpm --import 'https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key'
    - name: Copy RabbitMQ repository
      become: yes
      copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo
    - name: Install RabbitMQ
      become: yes
      yum:
        name:
          - socat
          - logrotate
          - erlang
          - rabbitmq-server
        state: present
    - name: Enable RabbitMQ systemd service
      become: yes
      systemd:
        daemon_reload: yes
        state: restarted
        name: "rabbitmq-server.service"
        enabled: yes
    - name: Add user to RabbitMQ
      become: yes
      shell: |
        rabbitmqctl add_user "{{ DP_RABBIT_USER }} {{ DP_RABBIT_PASSWORD }}"
        rabbitmqctl set_user_tags "{{ DP_RABBIT_USER }}" administrator
        rabbitmqctl set_permissions "{{ DP_RABBIT_USER }}" ".*" ".*" ".*"
    - name: Restart RabbitMQ service
      systemd:
        state: restarted
        name: "rabbitmq-server.service"
        enabled: yes
