---
- hosts: all
  vars:
    local_app_dir: "../"
    remote_home: "/home/ec2-user"
    remote_app_dir: "{{ remote_home }}/dp"
  vars_files:
    - vars.json
  tasks:
    - name: Install Golang and Protocol Buffers
      become: yes
      yum:
        name:
          - golang
          - protobuf-compiler
          - protobuf-devel
        state: present
    - name: Install Protocol Buffers Generators
      shell: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - name: Copy proto folders
      copy:
        src: "{{ local_app_dir }}/proto"
        dest: "{{ remote_app_dir }}/proto"
      register: app_proto
    - name: Compile Protocol Buffers
      shell: |
        cd "{{ remote_app_dir }}"
        protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative proto/*.proto
      environment:
        PATH: "{{ lookup('env', 'PATH') }}:{{ ansible_env.GOPATH }}/bin"
    - name: Copy Application
      copy:
        src:
          - "{{ local_app_dir }}/proto"
          - "{{ local_app_dir }}/pkg"
          - "{{ local_app_dir }}/main.go"
          - "{{ local_app_dir }}/go.mod"
          - "{{ local_app_dir }}/go.sum"
        dest: "{{ remote_app_dir }}"
      register: app
    - name: Compile Application
      shell: |
        cd "{{ remote_app_dir }}"
        go build -ldflags="-s -w" -o build/node cmd/server/main.go
    - name: Copy systemd unit file
      become: yes
      template:
        src: "dp.service.j2"
        dest: "/etc/systemd/system/dp.service"
    - name: Enable and start systemd service
      become: yes
      systemd:
        daemon_reload: yes
        state: restarted
        name: "dp.service"
        enabled: yes
